-- ═══════════════════════════════════════════════════════════════════════
--  ⚠️  DIESE DATEI IST ABSICHTLICH LEER — NICHT AUSFÜHREN
-- ═══════════════════════════════════════════════════════════════════════
--
--  Früher lag hier ein altes Schema mit 6 Tabellen. Das echte, aktuelle
--  Schema liegt in:
--
--      supabase/schema.sql
--
--  Dort sind 20 Tabellen, 38 RLS-Policies, Trust-Stufen, Profil-Erzeugung,
--  Spot-Verifizierung und Safety-Events definiert.
--
--  Ausführen in dieser Reihenfolge:
--    1. supabase/schema.sql            (in das SQL-Editor / psql)
--    2. node scripts/test_rls.js       (Negativ- und Positiv-Tests)
--
--  Diese Datei existiert nur, damit niemand versehentlich die alte
--  Version deployt. Sie enthält absichtlich keine DDL.
--
--  VERLAUF: Das alte Schema hatte 6 Tabellen ohne RLS. Wer es versehentlich
--  ausgeführt hat, sollte die Tabellen droppen und schema.sql neu laufen
--  lassen — sonst fehlen die RLS-Policies komplett.
